TBD54566975/ssi-sdk

cryptosuite/cryptosuite.go
cryptosuite/jsonwebkey2020.go
cryptosuite/jsonwebkey2020_test.go
cryptosuite/jwssignaturesuite.go
cryptosuite/jwssignaturesuite_test.go
vc/builder_test.go
vc/model.go

- Also added a configurable proof purpose

Add Verifiable Presentation Tests

---

cryptosuite/jsonwebkey2020.go

update rsa alg according to https://w3c-ccg.github.io/lds-jws2020/#jose-conformance

ps256 instead of rs256

---

README.md

Update README for JWS Suite Compliance

---

cryptosuite/jwt.go

Previous impl was using quoted string JSON as the `vp` and `vc` values. This lets the lestrrat library handle encoding.

Update JWT claim encoding

---

credential/exchange/model.go
credential/exchange/submission.go
credential/exchange/submission_test.go
credential/exchange/verification.go

- Tests for presentation definition, and submission logic
- A number of bug fixes that came up during testing

Presentation Exchange: Submission Tests

---

README.md
credential/known_schemas/wr-display-mapping-object.json
credential/known_schemas/wr-entity-styles.json
credential/known_schemas/wr-labeled-display-mapping-object.json
credential/rendering/model.go
credential/rendering/model_test.go
credential/rendering/schema.go
credential/rendering/schema_test.go
credential/test_vectors/wr-display-mapping-path-example-1.json
credential/test_vectors/wr-display-mapping-text-example-2.json
credential/test_vectors/wr-entity-styles-example-1.json
credential/test_vectors/wr-labeled-display-mapping-path-example-1.json
credential/test_vectors/wr-labeled-display-mapping-text-example-2.json

Object models, schemas, tests
https://identity.foundation/wallet-rendering/
Fixes https://github.com/TBD54566975/did-sdk/issues/52

Wallet Rendering Spec Support

---

credential/exchange/request.go
credential/exchange/schema.go
credential/exchange/submission.go
credential/exchange/submission_test.go
credential/exchange/verification.go
credential/manifest/schema.go
credential/rendering/schema.go
credential/schema/vcjsonschema.go
credential/signing/jwt.go
cryptosuite/jsonwebkey2020.go
cryptosuite/jwssignaturesuite.go
cryptosuite/jwt.go
did/key.go
go.mod
go.sum

Fixes https://github.com/TBD54566975/ssi-sdk/issues/68

Add logrus

---

credential/exchange/submission.go
credential/exchange/submission_test.go
credential/exchange/verification_test.go
cryptosuite/jsonwebkey2020.go

Fixes https://github.com/TBD54566975/ssi-sdk/issues/117

make claim format struct public

---

schema/known_schemas/cm-credential-manifest.json

link relied upon for CM schema moved, breaking the tests

update to latest cm schema

---

example/did/did_test.go
example/presentation/presentation_test.go
example/util_test.go
example/vc/vc_test.go

This runs the examples on tests. If an example has an issue and crashes / exits the test will fail. 
This makes sure our examples don't break and go unnoticed.

adding tests to example packages

---

did/web.go
did/web_test.go
go.mod
go.sum

DID Web tests use mock HTTP Resolvers

---

credential/exchange/builder_test.go
credential/exchange/model.go
credential/exchange/testdata/pe-definition-example-1.json
credential/manifest/builder_test.go
schema/known_schemas/pe-presentation-definition-envelope.json
schema/known_schemas/pe-presentation-definition.json

As per https://github.com/decentralized-identity/presentation-exchange/issues/361

Presentation Exchange: Required Constraints

---

.github/codecov.yml
README.md
did/key.go

- Exclude examples, util
- Codecov badge in README
- Typo fix

Basic codecov config

---

credential/exchange/request_test.go
credential/signing/jwt.go

was using `credential` instead of `vc`

fix jwt-vc

---

crypto/jwt_test.go
dwn/model.go
dwn/model_test.go
dwn/testdata/dwn-message-example-1.json
schema/known_schemas/dwn-message.json

Adding dwn message object. This will allow the ssi-service to process dwn messages

Adding dwn message objects

---

.github/workflows/golangci-lint.yml

This should fix the broken build in the `main` branch.

Add timeout to the linter

---

crypto/jwk.go
crypto/jwk_test.go
did/ion/operations.go

- expose private keys via getters
- able to convert from jwks back to go keys

ion fix and convert back to go keys from jwk

---

credential/signature_test.go

- https://github.com/TBD54566975/ssi-sdk/actions/runs/4734205247/jobs/8402793774
- Add more randomness to reduce intermittent failure

Fix flaky signature check test

---

.github/workflows/ci.yml
.github/workflows/golangci-lint.yml
CONTRIBUTING.md
README.md
credential/manifest/builder.go
credential/manifest/builder_test.go
credential/manifest/model.go
credential/manifest/testdata/cm-application-example-1.json
credential/manifest/testdata/cm-response-example-1.json
credential/manifest/testdata/cm-response-example-2.json
did/web/web_test.go
schema/known_schemas/cm-credential-application.json
schema/known_schemas/cm-credential-response.json

fixes #372 
update to the latest version of the spec

Credential Manifest: add applicant id

---

sd-jwt/README.md
sd-jwt/sd_jwt.go

Added readme section and todos properly

---

sd-jwt/example/main.go
sd-jwt/sd_jwt.go
sd-jwt/sd_jwt_test.go

Additionally also exported some additional methods.

Improve examples for sd-jwt

---

did/ion/operations_test.go
did/ion/resolver.go

To be used by consumers when they want to guarantee idempotency

Return did resolution result from anchor op

---

credential/integrity/signature.go
credential/integrity/signature_test.go

Pre-requisite for fixing https://github.com/TBD54566975/ssi-service/issues/122

Pass ctx for verification.

---

credential/manifest/model.go
credential/manifest/testdata/full-application.json
example/manifest/manifest.go
example/usecase/steel_thread/testdata/ca.json

adding applicant as required

---

did/ion/did_test.go
did/resolution/model.go
did/web/resolver.go

Added docs and fixed required fields for resolution

---

credential/model.go
credential/schema/access.go
credential/schema/access_test.go
credential/schema/model.go
credential/schema/model_test.go
credential/schema/vcjsonschema.go
credential/schema/vcjsonschema_test.go
credential/validation/validation_test.go
credential/validation/validators.go

- reworked schema validation logic to handle both credential and non credential types
- Added tests for all MUST values

VC JSON Schema compliance with latest spec

---

credential/exchange/request.go
credential/exchange/schema.go
credential/exchange/submission.go
credential/exchange/verification.go
credential/integrity/signature_test.go
credential/manifest/schema.go
credential/parsing/parsing.go
credential/rendering/schema.go
credential/schema/access.go
credential/status/statuslist2021.go
crypto/jwx/jwk.go
crypto/jwx/jws.go
crypto/keys.go
cryptosuite/jws2020/jsonwebkey2020.go
cryptosuite/jws2020/jwssignaturesuite.go
did/key/key.go
did/key/key_test.go
did/peer/peer.go
did/peer/peer0.go
did/peer/peer2.go
did/pkh/pkh.go
did/resolution/resolver.go
did/util.go
example/usecase/employer_university_flow/pkg/verifier.go
schema/jsonschema.go

this leads to much better readability of error chains

Refactoring so error causality is easier to follow

---

.github/workflows/ci.yml
.github/workflows/golangci-lint.yml
CONTRIBUTING.md
README.md
go.mod
go.sum
go.work
sd-jwt/README.md

Upgrade go version
