TBD54566975/ssi-sdk

.github/workflows/codeql-analysis.yml, credential/schema/model.go, credential/schema/vcjsonschema.go, credential/schema/vcjsonschema_test.go, go.mod, go.sum, schema/jsonschema.go, schema/jsonschema_test.go
Was not validating JSON Schemas correctly
=> Fix schema validation logic

util/helpers.go, util/helpers_test.go
[json-gold](https://github.com/piprate/json-gold) does have the caching document loader implemented (RFC7324)
It is enabled by passing the caching loader into the ldProcessor options
Added it as the default option [here](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers.go#L44).
Json-ld context can be loaded as a json-ld document (type map[string]interface{}) using the loadDocument function [test example](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers_test.go#L115)
or further converting it into a json-gold.Context object [test example](https://github.com/singyiu/ssi-sdk/blob/c1f4324e9d365481dde54b47af76be47e0f82b67/util/helpers_test.go#L134)
A helper function "GetContextFromMap" was added.
=> json-ld cached doc loader

credential/status/statuslist2021.go, credential/status/statuslist2021_test.go
the status list check was failing, due to the `CredentialStatus` property being an interface type. Type information can be lost, making the cast fail. Marshaling and unmarshaling into the object, and using the go struct validator is a safer way to do the check.
=> remove casting from status list check

cryptosuite/jsonwebkey2020.go
This is related to: https://github.com/TBD54566975/ssi-sdk/issues/104..
=> removed go build annotation to fix Issue #104

credential/signing/jwt.go, cryptosuite/jwt.go
related to https://github.com/lestrrat-go/jwx/issues/670 "You don't need to add build tags to your source code.".
=> fix: remove build tags

examples/vc/vc.go
please merge https://github.com/TBD54566975/ssi-sdk/pull/126 first then this will follow: 
```
➜  vc git:(vc-example) go run vc.go
Created Verifiable Credential:
{
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://www.w3.org/2018/credentials/examples/v1"
],
"id": "http://example.edu/credentials/1872",
"type": [
"VerifiableCredential",
"AlumniCredential"
],
"issuer": "https://example.edu/issuers/565049",
"issuanceDate": "2010-01-01T19:23:24Z",
"credentialSubject": {
"alumniOf": {
"id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
"name": [
{
"lang": "en",
"value": "Example University"
},
{
"lang": "fr",
"value": "Exemple d'Université"
}
]
},
"id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
}```
=> verifiable credential example

examples/did/did.go
This PR fixes a typo in `examples/did`
=> examples/did: Fix typo

.github/workflows/ci.yml, magefile.go
=> add codecov

credential/exchange/builder.go
removes the print statement and marshaling in the builder on the exchange layer. There is no good reason to force a print here i think.
=> remove print and json marshalling in builder at exchange layer

cryptosuite/jsonwebkey2020.go
This new function coverts a ed25519.PrivateKey to a JsonWebKey2020
This pr is for this issue - https://github.com/TBD54566975/ssi-sdk/issues/160
=> Adding new function that converts a ed25519 key to JWK

codecov.yml, schema/jsonschema_test.go
- util and examples have been excluded for now
=> Test coverage for: Schemas

crypto/jwk.go, crypto/jwk_test.go, cryptosuite/jsonwebkey2020.go, cryptosuite/jsonwebkey2020_test.go, cryptosuite/jwssignaturesuite_test.go, did/key.go, did/key_test.go
Prereq for https://github.com/TBD54566975/ssi-service/issues/105
Mostly shuffling things around to further decouple data integrity suites from JWKs.
=> Construct JWKs generically from public and private keys

crypto/jwk_test.go, crypto/jwt.go, crypto/keys.go, crypto/keys_test.go, crypto/models.go, cryptosuite/jsonwebkey2020.go, did/key.go, did/key_test.go, did/model.go, did/model_test.go, did/util.go, example/did/did.go, example/wallet.go
the key type was not maintained, leading to signing errors
=> reconstruct priv key better

crypto/models.go, did/model.go, did/peer.go, did/peer_test.go, did/util.go
adding more test coverage to did peer. https://github.com/TBD54566975/ssi-sdk/issues/209
=> added better test code coverage for did peer

crypto/jwt.go, crypto/jwt_test.go
do not add kid to a jwt body
add jws parsing
=> add jws parsing

credential/exchange/request_test.go, credential/exchange/submission_test.go, credential/manifest/validation_test.go, credential/signing/jwt_test.go, credential/util/util_test.go, crypto/jwk.go, crypto/jwt.go, crypto/jwt_test.go, cryptosuite/jsonwebkey2020.go, example/presentation/presentation.go, example/usecase/apartment_application/apartment_application.go, example/usecase/employer_university_flow/main.go, example/usecase/employer_university_flow/pkg/util.go, example/usecase/steel_thread/steel_thread.go
Support generating generic JWK objects. Add validation so that it's impossible to generate signers/verifiers with unsupported key types/algorithms.
=> Fix jwk usage

credential/manifest/validation_test.go, credential/verification/verification_test.go, go.mod, go.sum, magefile.go, schema/jsonschema.go, schema/jsonschema_test.go
Fixes #231. New lib which supports the newer drafts of json schema.
=> Update json schema lib

.golangci.yaml, did/key.go, did/key_test.go, did/peer.go, did/util.go, did/web.go
This PR exposes the key type used when decoding the DIDKey. This is needed as otherwise the information would be lost when decoding.
This is a prerequisite to fixing https://github.com/TBD54566975/ssi-service/issues/181. 
Note that I had to update some examples of the tests, since the test vectors appear to have been incorrectly generated.
=> Fix key type issue

credential/exchange/verification.go, credential/exchange/verification_test.go, credential/util/util.go
This fixes a bug where the presentations were throwing errors when the verifiable credentials contained in them were JWTs (instead of elements of type `VerifiableCredential`).
The test I added fails before the changes, and passes after the updates.
=> Fix verification bug with JWT credentials

credential/schema/vcjsonschema_test.go, schema/jsonschema.go, schema/known_schemas/vc-json-schema.json
as per https://github.com/w3c-ccg/vc-json-schemas/pull/112
=> update vc json schema

.github/workflows/ci.yml, did/key_fuzz_test.go, did/key_test.go, magefile.go
WIP PR for [issue#261](https://github.com/TBD54566975/ssi-sdk/issues/261)
Adds:
- fuzz test for "Create and then resolve returns a document with the same ID".
- Unit tests for "Generate and then resolve returns a document with the same ID".
With commands:
`mage fuzz`
`mage test`
=> [WIP] #261: Add fuzz test

credential/manifest/schema_test.go
This makes tests run significantly faster. See below, where:
* Before changes: `32.108`
* After changes: `11.448`
```
➜  ssi-sdk git:(main) go clean -testcache; time go test -tags=jwx_es256k ./...             
ok      github.com/TBD54566975/ssi-sdk/credential       0.200s
ok      github.com/TBD54566975/ssi-sdk/credential/exchange      5.440s
ok      github.com/TBD54566975/ssi-sdk/credential/manifest      31.147s
ok      github.com/TBD54566975/ssi-sdk/credential/rendering     0.293s
ok      github.com/TBD54566975/ssi-sdk/credential/schema        0.342s
ok      github.com/TBD54566975/ssi-sdk/credential/signing       0.474s
ok      github.com/TBD54566975/ssi-sdk/credential/status        0.228s
ok      github.com/TBD54566975/ssi-sdk/credential/util  1.248s
ok …
```
=> Enable schema caching for tests

.golangci.yaml, credential/signing/jws.go, credential/signing/jws_test.go, crypto/jwt.go, magefile.go
This fixes https://github.com/TBD54566975/ssi-sdk/issues/272
=> Added signing utilities for vc-jws, with the appropriate content type.

credential/status/statuslist2021.go, credential/status/statuslist2021_test.go
This change allows us to use a StatusList2021Entry or a map[string]interface as our credStatus object.
=> adding statuslist conversion

.github/workflows/ci.yml, .github/workflows/golangci-lint.yml, CONTRIBUTING.md, README.md
=> Uptake latest go

oidc/issuance/example_issuer_metadata.json, oidc/issuance/metadata.go, oidc/issuance/metadata_test.go, util/url.go, util/url_test.go
This is based in the spec section https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-issuer-metadata
I believe the SDK is the best home for this. My expectation is that other folks will need to support this kind of models, and providing a library to do so easily will be beneficial to the community. 
I thought about separating it into it's own module, but given that we're packaging all functionality into the SDK, I believe this is the best place for this to live.
=> Add models for Credential Issuer Metadata

CONTRIBUTING.md
This fixes https://github.com/TBD54566975/ssi-sdk/issues/290
=> Added style and best practices

credential/exchange/request_test.go, did/key.go, did/peer.go, did/pkh.go, did/resolver.go, did/resolver_test.go, did/web.go
update the resolver interface to support multiple methods per resolver as an option.
enforced interface compliance for resolvers in the sdk.
=> multi method resolver

did/key.go, did/model.go, did/util.go, did/util_test.go
- Already existed in a lesser from in the service, this will be uptaken there
=> Get Key from a DID's Verification Information

credential/exchange/request.go, credential/exchange/request_test.go, credential/exchange/submission_test.go, credential/exchange/verification.go, credential/exchange/verification_test.go, credential/signing/jws.go, credential/signing/jwt.go, credential/signing/jwt_test.go, credential/util/util.go, crypto/jwt.go, crypto/jwt_test.go, example/presentation/presentation.go, example/usecase/apartment_application/apartment_application.go, example/usecase/employer_university_flow/main.go, example/usecase/employer_university_flow/pkg/util.go, example/usecase/employer_university_flow/pkg/verifier.go, util/errors.go
- support extracting headers from JWTs, useful for getting `kid` and other info needed in verification
- for a logging err, check if err is nil, which was resulting in returning a nil value when an error was expected
=> Add JWT header extraction; fix errs

credential/exchange/builder_test.go, credential/exchange/model.go, credential/exchange/request.go, credential/exchange/request_test.go, credential/exchange/submission.go, credential/exchange/submission_test.go, credential/exchange/verification.go, credential/exchange/verification_test.go, credential/manifest/testdata/full-credential.json, credential/manifest/testdata/full-manifest.json, credential/manifest/validation.go, credential/signing/jwt.go, credential/signing/jwt_test.go, credential/util/util.go, credential/util/util_test.go, example/usecase/apartment_application/apartment_application.go, example/usecase/steel_thread/testdata/cm.json, example/usecase/steel_thread/testdata/vc.json
fixes #350, #165, and partially #64
=> Presentation Exchange: support for json schema filtering and relational constraints

credential/exchange/request.go, credential/exchange/request_test.go, credential/exchange/submission.go, credential/exchange/submission_test.go, credential/exchange/verification_test.go, credential/jws.go, credential/jwt.go, credential/jwt_test.go, credential/signature.go, credential/util_test.go, crypto/jwx/jwk.go, crypto/jwx/jwk_test.go, crypto/jwx/jws.go, crypto/jwx/jws_dilithium_test.go, crypto/jwx/jwt.go, crypto/jwx/jwt_test.go, crypto/keys.go, cryptosuite/jsonwebkey2020.go, cryptosuite/jsonwebkey2020_test.go, cryptosuite/jwssignaturesuite_test.go, did/ion/crypto.go, did/ion/operations.go, did/jwk.go, did/jwk_test.go, did/key.go, example/presentation/presentation.go, example/usecase/employer_university_flow/pkg/util.go
=> Refactor JWX logic to reduce dep on JWX lib

did/resolution/model.go, did/resolution/resolver_test.go
The resolution validation code was failing due to the following: 
If you go to validator.v10 docs:
https://github.com/go-playground/validator/blob/c8b98cbcea08971fbead222ddf5fd406a40d40ed/validator_test.go#L12041
You will see that it requires to specify format of datetime string, otherwise, this test will fail: 
```go
t.Run("test valid time", func(t *testing.T) {
now := time.Now().UTC().Format(time.RFC3339)
var metadata = DocumentMetadata{
Created: now,
}
assert.True(t, metadata.IsValid())
})
```
with the datetime validation failing. I have added a test to validate that the created field can properly be validate against the resolution metdata, and that the datetime field for validator is compared against RFC3339 specification (see below)
=> Fix resolution metadata validation with datetime

did/ion/did.go, did/ion/did_test.go, did/ion/enum.go, did/ion/model.go, did/ion/operations.go, did/ion/operations_test.go, did/ion/request.go, did/ion/request_test.go, did/ion/resolver.go, did/jwk/resolver.go, did/key/resolver.go, did/peer/peer.go, did/peer/peer0.go, did/peer/peer2.go, did/peer/resolver.go, did/pkh/resolver.go, did/resolution/model.go, did/resolution/resolver.go, did/web/resolver.go, go.work.sum
#349 
adds the ability to reconstruct any ION DID's state from a set of patches
=> Support ION DID Reconstruction & Long Form DID resolution

credential/model.go, credential/schema/model.go, credential/schema/testdata/jsonschemacredential-schema-1.json, credential/schema/vcjsonschema.go, credential/schema/vcjsonschema_test.go
- Add enforcement of credential schema for json schema credentials and associated tests
=> JSON Schema - include latest spec updates around CredSchema/digestSRI

did/peer/peer0.go, did/peer/peer0_test.go, did/web/web.go, did/web/web_test.go
merge in https://github.com/TBD54566975/ssi-sdk/pull/430
=> Fix/did web create key (#461)

sd-jwt/README.md
I was going through the README.md of sd-jwt and noticed a small typo that I believe needs correction. Here are the details:
```
$ go run example.main.go
stat example.main.go: no such file or directory
$ go run example/main.go
Combined Issuance Format
eyJhbGciOiJFUzI1NiIsInR5cCI6Ikp...
```
=> Fix typo in Quick Start command in README.md

credential/builder.go, credential/builder_test.go, credential/status/statuslist2021.go, example/manifest/manifest.go, example/usecase/apartment_application/apartment_application.go, example/usecase/steel_thread/steel_thread.go, go.work.sum
Address Issue #400 .
Changes default id in NewVerifiableCredentialBuilder as empty, validates if id is a parsable uri in SetID
=> Update ID rules in NewVerifiableCredentialBuilder
